modLoader="javafml"
loaderVersion="[44,)"
license="MIT"
issueTrackerURL="https://github.com/anviaan/SculkHorn/issues"

[[mods]]
modId="sculkhornid"
version="1.2.0"
displayName="Sculk Horn Mod"
updateJSONURL="https://anvian-page.netlify.app/forge/sculkhornid.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sculk-horn"
logoFile="icon.png"
authors="anvian"
description="Create a Sonic Shock from a Area Sculk Horn and create a Sonic Boom from a Range Sculk Horn"
[[dependencies.sculkhornid]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sculkhornid]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
