modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/anviaan/SculkHorn/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://anvian-page.netlify.app/forge/sculkhornid.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sculk-horn"
logoFile="icon.png"
authors="${mod_authors}"
credits="PinhaColada2222"
displayTest="MATCH_VERSION"

description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
